// <auto-generated />
using System;
using Infrastructure.DataAccess.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.DataAccess.EntityFramework.Migrations
{
    [DbContext(typeof(ChallengeDbContext))]
    partial class ChallengeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.RatingEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<uint>("CraftsmanId")
                        .HasColumnType("oid")
                        .HasColumnName("craftsman_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("CustomerId")
                        .HasColumnType("oid")
                        .HasColumnName("customer_id");

                    b.Property<uint>("Score")
                        .HasColumnType("oid")
                        .HasColumnName("score");

                    b.Property<uint>("TaskId")
                        .HasColumnType("oid")
                        .HasColumnName("task_id");

                    b.HasKey("Id");

                    b.HasIndex("Id", "CraftsmanId");

                    b.ToTable("ratings", "public");
                });
#pragma warning restore 612, 618
        }
    }
}
